### ISSUE TITLE
关于输入数据大小

### ISSUE THREAD

**Issue by Liu6697** [zacario-li/Fast-SCNN_pytorch#2]
作者你好，原文中网络的输入大小是1024x2048，而您在这里的输入大小是320x320？请问您是如何将输入数据与网络输入大小匹配的？另外问一下作者您有没有用aeroscapes训练过这个网络？他的图片大小是1280*720。

**Comment by zacario-li** [comment]
@Liu6697 首先，明确一下，这个网络对于图像输入的尺寸没有要求，我320x320只是任意选了一个尺寸，为了训练快速。我使用的是voc2012，没有使用aeroscapes训练。图片尺寸无所谓，只要保证是(1,2,3,6)的公倍数即可。

**Comment by zacario-li** [comment]
@Liu6697 如果你需要任意尺寸，那么请修改 fastscnn.py:FeatureFusion()类，
`xUp = F.interpolate(ph2Feature, scale_factor=self.scale, mode='bilinear', align_corners=True)`
为
`xUp = F.interpolate(ph2Feature, size=ph1Feature.shape[2:], mode='bilinear', align_corners=True)

**Comment by zacario-li** [comment]
@Liu6697 训练时，会基于你选择的输入尺寸，在数据集上随机crop。在你部署到项目时，首先看一下你采集到的图片的尺寸，然后看看能不能训练一个同样输入大小的网络。如果有困难，那么把采集图片均分成若干份，然后用若干份小图的尺寸训练一个网络，最后把预测结果拼接成大图。
切忌将原图resize，这样就很不精准了。

**Comment by Liu6697** [comment]
好的，十分感谢！我终于训练上了！
