### ISSUE TITLE
Pretrained model in a host?

### ISSUE THREAD

**Issue by Tomyxtrejo** [zacario-li/Fast-SCNN_pytorch#3]
Hello, can you please upload it to google drive or a host without register required?

**Comment by zacario-li** [comment]
Sorry for that, I trained the model with private dataset, I can not share it. B.T.W train this model is very easy, try it by yourself.
Maybe later I can train it with voc2012

**Comment by Tomyxtrejo** [comment]
I'm noob in this technologies, idk how to train. I'm trying to find some way to do real time human segmentation in low requirements hardware... like i saw in tiktok and other chinesse apps
