### ISSUE TITLE
dice训练失败  交叉熵可以

### ISSUE THREAD

**Issue by zhangyunming** [zacario-li/Fast-SCNN_pytorch#4]
你好，很好用的代码，感谢分享。
       【1】我训的是两类的0，1数据，用dice loss训练失败，说是：Class values must be smaller than num_classes
 我用的1.3版本的pytorch，训练交叉熵的可以。我看原文就用的这个。
      【2】辅助loss的权重是0.4，main loss不需要×0.6吗
      【3】测试的时候，你吧图片进行了多部分画块，然后每块都进行分割，再组合，这样不是做了多次前向，时间耗时上去了吗？
      【4】你每个epoch的打印一次信息，我有20w的数据，一直没出信息，我以为挂了呢。。。

**Comment by zacario-li** [comment]
@zhangyunming 感谢你喜欢我写的代码。
1：看起来，你的lable做的可能不匹配。如果你的类别只有0和1，那么你的label做完后，变成one_hot，你应该只有两个channel，你可以检查下这部分。
2：这个地方main loss是根据你自己的数据集设定一个比较合理的比例，原作者论文针对的是Cityscapes，你需要根据自己的情况，选择合适的比例。
3：是的，我切成了多块，最后拼接。这样一定是增加耗时的，我这么做的目的，是为了精准还原像素预测的位置，如果你resize了，那很明显，很多地方都是插值出来的分割mask，这样做效果很差。所以我的建议是，如果你要精确的mask，那么你一定不要resize。
4：log打印那块，我还没有好好改，我是想改到tensorboard中的，但是实在没有时间，抱歉。

**Comment by zhangyunming** [comment]
dice loss 之前训不起来  是因为pytorch的版本问题 改成1.3版本，可以训练
