### ISSUE TITLE
question about FPS

### ISSUE THREAD

**Issue by amiraliAI** [zacario-li/Fast-SCNN_pytorch#5]
Hi dear,
How much is your inference FPS with video?
thanks

**Comment by zacario-li** [comment]
> Hi dear,
> How much is your inference FPS with video?
> thanks

It depends.
please refer to the code below:
[this code](https://github.com/zacario-li/Fast-SCNN_pytorch/blob/130cd421bf5501f447711ad2bdbc633f37419666/models/fastscnn.py#L264)
In my computer, set input size as [1, 3, 1000, 1000] on TITAN Xp, the inference FPS is 125.63
The whole processing time of a frame of the video, that's a complicated task, a bunch of skills would speed up the process.

**Comment by amiraliAI** [comment]
Yes. You right. but When I run model on video file it gives 13 frames per seconds unforchunetly.

**Comment by zacario-li** [comment]
> Yes. You right. but When I run model on video file it gives 13 frames per seconds unforchunetly.

I guess the pre-processing and post-processing cost you lots of time.
In a production deployment, we always define 3 threads to do it:
- Thread1:
pre-processing each frame from a video, then put the frame into a frame-queue
- Thread2:
your deep learning model, retrieve the data from the queue, inference it then put the result tensor in tensor-queue
- Thread3:
post-processing each tensor from tensor-queue

run the 3 threads at the same time, that can reduce your whole processing time.
